config/routes.rb
Rails.application.routes.draw do

  resources :locations

  root 'welcome#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new    
  end

  def create
    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenBnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= form_for :location, url: locations_path do |f| %>
  <p>
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>

  <p>
    <% f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>